using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ContractGen;

// Source generator: на каждый файл *.contract из проекта генерирует
//   namespace Contracts.V1 { public sealed class OrderCreated { ... } }
//   ...
//   Contracts.OrderCreatedVersions.All — список версий с типами и описанием изменений.
//
// Одно и то же имя OrderCreated в разных namespace изображает разные версии NuGet-пакета с контрактами:
// у строго сервиса — Contracts.V1.OrderCreated, у нового — Contracts.V4.OrderCreated.
[Generator]
public sealed class ContractGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor BadSpec = new(
        id: "CG001",
        title: "Ошибка в описании контракта",
        messageFormat: "{0}, строка {1}: {2}",
        category: "ContractGen",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var files = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith(".contract"))
            .Select((f, ct) => (Path: f.Path, Text: f.GetText(ct)?.ToString() ?? ""));

        context.RegisterSourceOutput(files, (spc, file) =>
        {
            ContractSpec spec;
            try
            {
                spec = ContractSpec.Parse(file.Text);
            }
            catch (SpecException e)
            {
                // Ошибка в описании -> ошибка компиляции
                spc.ReportDiagnostic(Diagnostic.Create(BadSpec, Location.None, FileName(file.Path), e.Line, e.Message));
                return;
            }

            spc.AddSource($"{spec.Name}.g.cs", SourceText.From(Render(spec), Encoding.UTF8));
        });
    }

    private static string Render(ContractSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Сгенерировано ContractGen из описания контракта.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var v in spec.Versions)
        {
            sb.AppendLine($"namespace Contracts.V{v.Number}");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>{spec.Name}, версия {v.Number}: {Escape(v.Change)}</summary>");
            sb.AppendLine($"    public sealed class {spec.Name}");
            sb.AppendLine("    {");
            foreach (var f in v.Fields)
            {
                var type = ContractSpec.KnownTypes[f.Type];
                var init = type == "string" ? " = \"\";" : "";
                sb.AppendLine($"        public {type} {f.Name} {{ get; set; }}{init}");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("namespace Contracts");
        sb.AppendLine("{");
        sb.AppendLine($"    public static class {spec.Name}Versions");
        sb.AppendLine("    {");
        sb.AppendLine($"        public const string EventType = \"{spec.Name}\";");
        sb.AppendLine();
        sb.AppendLine("        public static readonly global::System.Collections.Generic.IReadOnlyList<global::Contracts.ContractVersion> All = new[]");
        sb.AppendLine("        {");
        foreach (var v in spec.Versions)
            sb.AppendLine($"            new global::Contracts.ContractVersion({v.Number}, typeof(global::Contracts.V{v.Number}.{spec.Name}), \"{Escape(v.Change)}\"),");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string FileName(string path) => path.Substring(path.LastIndexOfAny(new[] { '/', '\\' }) + 1);

    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
